// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToDoApplication.Database.Models;

public partial class ToDo
{
    public long Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreateDate { get; set; }
}